name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        cargo build --release --verbose
        upx --lzma --best target/release/dnsrelay
      
    - name: upload_dnsrelay
      uses: actions/upload-artifact@v2
      with:
        name: output_dnsrelay
        path: target/release/dnsrelay
